spring:
  main:
    web-application-type: NONE
  datasource:
    username: ""
    password: ""
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    hibernate.ddl-auto: none



