spring:
  main:
    web-application-type: NONE
  datasource:
    username: ""
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: false
    hibernate.ddl-auto: none

logging: #Logback config for production
  config: classpath:logback.groovy


